---
project_name: heartbeats
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: heartbeats
    main: ./main.go
    binary: heartbeats
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}
dockers_v2:
  - dockerfile: Dockerfile
    platforms: [linux/amd64, linux/arm64]
    images:
      - ghcr.io/containeroo/heartbeats
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - internal
      - pkg
      - web
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "{{ .ProjectName }}"
      org.opencontainers.image.url: https://github.com/containeroo/heartbeats
      org.opencontainers.image.source: https://github.com/containeroo/heartbeats
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "GNU General Public License v3.0"
    flags:
      - --pull
      - --build-arg
      - LDFLAGS=-s -w -X main.Version={{ .Tag }} -X main.Commit={{ .FullCommit }}

archives:
  - formats: ["tar.gz"]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256
