---
heartbeats:
  alertmanager-prod:
    description: Production AlertManager health check
    interval: 30s
    grace: 10s
    receivers:
      - platform-team

  grafana-staging:
    description: Grafana heartbeat check for staging environment
    interval: 15s
    grace: 5s
    receivers:
      - observability-team

receivers:
  platform-team:
    slack_configs:
      - channel: platform-alerts
        token: env:HEARTBEATS_SLACK_TOKEN
        titleTmpl: "[HEARTBEAT] {{ .Name }} {{ upper .Status }}"
        textTmpl: |
          *Service:* {{ .Name }}
          *Status:* {{ .Status }}
          *Description:* {{ .Description }}
          *Last ping:* {{ if isRecent .LastPing }}just now{{ else }}{{ ago .LastPing }} ago{{ end }}

  observability-team:
    slack_configs:
      - token: file:tokens.txt//observability
        channel: observability
        titleTmpl: "[HEARTBEAT] {{ .Name }} {{ upper .Status }}"
        textTmpl: |
          **Service:** {{ .Name }}
          **Status:** {{ .Status }}
          **Description:** {{ .Description }}
          **Last ping:** {{ if isRecent .LastPing }}just now{{ else }}{{ ago .LastPing }} ago{{ end }}

  dev-crew-int:
    slack_configs:
      - channel: test
        token: env:HEARTBEATS_SLACK_TOKEN
        title: Heartbeat {{ .Name }} {{ upper .Status }}
        text: |
          *Description:*
          {{ .Description }}.
          Last ping: {{ if isRecent .LastPing }}now{{ else }}{{ ago .LastPing }}{{ end }}
    email_configs:
      - smtp:
          host: smtp.gmail.com
          port: 587
          from: giottolino.hq@gmail.com
          username: giottolino.hq@gmail.com
          password: env:HEARTBEATS_GMAIL_PASSWORD
          startTLS: true
        email:
          isHTML: true
          to: ["giottolino@gmail.com"]
