---
apiVersion: v1
kind: Service
metadata:
  name: heartbeats
  namespace: heartbeats
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
  selector:
    app: heartbeats
